import json
import os

pages = [
    { "type": "cover", "title": "A Gentle Reminder", "subtitle": "For you, for us, for healing." },
    { "type": "blank" },
    { "type": "title", "content": "A Gentle Reminder" },
    { "type": "content", "header": "Dedication", "text": ["To anyone who has ever looked back with regret and wished they had known better.", "And to the ones who stayed, waiting for us to figure it out."] },
    { "type": "content", "header": "Before You Begin", "text": ["This is not a book that will tell you what you want to hear.", "It will not make excuses for your behavior, and it will not pretend that apologies magically fix everything.", "But it is also not a book that will ask you to hate yourself forever.", "It is written with the belief that you can look honestly at the ways you have failed, without believing that you are a failure.", "Take your time with these pages. Read them when you need to be held accountable, and read them when you need to be forgiven."] },
    { "type": "content", "header": "Introduction", "text": ["We all make mistakes.", "Sometimes, we hurt the people who love us the most. Not because we want to, but because we are still learning how to heal ourselves.", "This is a gentle reminder that you are capable of change. You are capable of being better, for yourself and for the people you love.", "You cannot undo every mistake, but you can become someone who no longer repeats it."] },
    { "type": "content", "header": "How to Use This Book", "text": ["Treat this like a quiet conversation.", "Some pages are short, meant to be read on days when everything feels heavy.", "Other pages ask you to reflect. Be honest when you answer those.", "If you find a page that speaks directly to your current situation, bookmark it. Return to it.", "You don't have to read it all at once. Let it be a companion on your journey to becoming someone you can be proud of."] },
    { "type": "toc" },

    # CHAPTER 1
    { "type": "chapter_divider", "chapterNumber": "Chapter I", "chapterTitle": "Begin Here" },
    { "type": "content", "header": "The Courage to Look", "text": ["You are here because something needs to change.", "You have realized that the way you have been navigating your relationships, your emotions, or your reactions is no longer working.", "Admitting this is incredibly painful.", "It is much easier to blame others, to defend your actions, or to pretend that everything is fine.", "But you are choosing to look in the mirror.", "That is the hardest, but most important, first step."] },
    { "type": "content", "header": "Dropping the Defense", "text": ["When we are told that our actions hurt someone, our first instinct is often to build a wall.", "We explain our intentions. We point out what they did wrong. We say, 'But I didn't mean to.'", "Intentions do not erase impact.", "The beginning of change requires you to lower your weapons.", "You must learn to hear 'You hurt me' without immediately replying with 'But...'"] },
    { "type": "reflection", "prompt": "What am I avoiding admitting to myself?" },
    { "type": "content", "header": "The Uncomfortable Truth", "text": ["Change is not a switch you flip.", "It is not a realization you have once and then suddenly you are a perfect person.", "It is a slow, uncomfortable, and often frustrating process of unlearning.", "You will have to unlearn how you handle anger. You will have to unlearn how you protect your ego. You will have to unlearn the ways you have been taught to communicate.", "It will feel unnatural at first.", "Do it anyway."] },
    { "type": "special", "header": "Read This When You Feel Like You Are Not Enough", "text": ["You are looking at your flaws and feeling overwhelmed.", "You are wondering how anyone could love someone who still has so much to fix.", "But remember this: perfection is not a requirement for love.", "Effort is.", "Consistency is.", "A willingness to grow is.", "You are enough, exactly as you are, to begin the work of becoming better."] },
    { "type": "content", "header": "The Myth of Overnight Healing", "text": ["Do not expect applause for finally doing the bare minimum.", "Do not expect the people you hurt to immediately trust you just because you have decided to change.", "Trust is built in drops and lost in buckets.", "You are currently refilling the bucket.", "It will take time.", "Be patient with the process, and be patient with the people waiting for you to prove it."] },
    { "type": "content", "header": "A Small Reminder", "text": ["You are not the worst thing you have ever done.", "But you are also not just the good intentions you hold in your head.", "You are what you do from this moment forward."] },

    # CHAPTER 2
    { "type": "chapter_divider", "chapterNumber": "Chapter II", "chapterTitle": "The Things We Don't Like About Ourselves" },
    { "type": "content", "header": "The Shadow", "text": ["We all have parts of ourselves we wish we could surgically remove.", "The jealousy. The anger. The insecurity. The selfishness. The emotional immaturity.", "We hide them because we are afraid that if anyone truly saw them, they would leave.", "But hiding them does not make them disappear. It only gives them power in the dark.", "The only way to strip them of their power is to drag them into the light and say, 'I see you. I own you. But you no longer control me.'"] },
    { "type": "content", "header": "Where Anger Comes From", "text": ["Anger is rarely the first emotion.", "Anger is the bodyguard. It steps in to protect you when you feel embarrassed, misunderstood, rejected, or afraid.", "The next time you feel the heat of anger rising in your chest, pause.", "Ask yourself: What is the softer emotion underneath this?", "Are you actually angry, or are you just afraid of not being heard?"] },
    { "type": "reflection", "prompt": "What do I usually do when I feel insecure or threatened?" },
    { "type": "content", "header": "The Ego's Trick", "text": ["Your ego will tell you that admitting you are wrong makes you weak.", "It will tell you that apologizing is a form of losing.", "This is a lie.", "It takes immense strength to look someone in the eye and say, 'I was wrong. I handled that poorly. I am sorry.'", "Weakness is doubling down on a mistake because you are too fragile to admit it."] },
    { "type": "content", "header": "Selfishness in Disguise", "text": ["Sometimes, our 'love' is actually just attachment.", "We want the other person to act in ways that make us comfortable.", "We want them to heal on our timeline.", "We want them to forgive us quickly so we don't have to sit with the discomfort of our guilt.", "True love requires stepping outside of your own needs and holding space for theirs."] },
    { "type": "special", "header": "Read This When You Hate Yourself", "text": ["You have realized the extent of your flaws, and the weight of it is crushing you.", "You feel toxic, broken, and unworthy.", "Please listen: Self-hatred is a lazy emotion.", "It feels like accountability, but it is actually an escape.", "If you simply hate yourself, you don't have to do the hard work of changing.", "Instead of hating yourself, take responsibility. Hate the action, not the person.", "You are a human being who is still learning."] },
    { "type": "content", "header": "Embracing the Flaws", "text": ["You do not need to eradicate every negative trait to be a good partner.", "You just need to be aware of them.", "Awareness gives you the critical half-second between feeling an impulse and acting on it.", "In that half-second, you have a choice.", "That choice is the difference between who you were yesterday and who you are today."] },

    # CHAPTER 3
    { "type": "chapter_divider", "chapterNumber": "Chapter III", "chapterTitle": "You Are Responsible, But You Are Not Hopeless" },
    { "type": "content", "header": "The Line Between Guilt and Shame", "text": ["Guilt says, 'I did a bad thing.'", "Shame says, 'I am a bad person.'", "Guilt is productive. It is your conscience telling you that your actions did not align with your values. It motivates you to repair the damage.", "Shame is destructive. It tells you there is no point in trying because you are inherently flawed.", "You must learn to listen to guilt and reject shame."] },
    { "type": "content", "header": "Owning the Impact", "text": ["When you hurt someone, their reaction is about their pain, not your character.", "Do not make their pain about you.", "If they are crying, do not say, 'Well now I feel like a monster.'", "That forces them to stop expressing their hurt and start comforting you.", "Be strong enough to sit in the discomfort of knowing you caused it, without needing them to make you feel better."] },
    { "type": "reflection", "prompt": "How do I usually react when someone tells me I hurt them?" },
    { "type": "content", "header": "The Danger of Excuses", "text": ["'I only did it because I was stressed.'", "'I yelled because you provoked me.'", "'I wouldn't have lied if you weren't so easily upset.'", "These are not apologies. These are justifications.", "You are responsible for your reactions, regardless of the circumstances.", "Until you accept 100% responsibility for your actions, you cannot change them."] },
    { "type": "special", "header": "Read This When You Think You Ruined Everything", "text": ["You made a mistake.", "Maybe it was a big one. Maybe it was the same small one for the hundredth time.", "You feel like the bridge is burned and the damage is irreversible.", "Take a deep breath.", "Unless you have completely broken a non-negotiable boundary, most things can be repaired with genuine, consistent effort.", "Do not give up just because it got hard.", "Go apologize. And then do better."] },
    { "type": "content", "header": "Action Over Words", "text": ["An apology without changed behavior is just manipulation.", "You can write poetry about how sorry you are. You can cry. You can promise the stars.", "But if you wake up the next day and do the exact same thing, your words mean nothing.", "The best apology is changed behavior."] },
    { "type": "content", "header": "Hope in Action", "text": ["You are not hopeless.", "The fact that you are reading these words, the fact that you care enough to try, proves that there is goodness inside you.", "You have the capacity for deep empathy, profound love, and incredible growth.", "You just have to choose it.", "Over, and over, and over again."] },

    # CHAPTER 4
    { "type": "chapter_divider", "chapterNumber": "Chapter IV", "chapterTitle": "The Weight of Guilt" },
    { "type": "content", "header": "Carrying the Stone", "text": ["Guilt is a heavy stone to carry in your chest.", "It wakes you up in the middle of the night. It replays your worst moments on a loop.", "It tells you that you do not deserve happiness because of the pain you caused.", "But carrying that stone forever does not serve anyone. It does not heal the person you hurt.", "It only exhausts you."] },
    { "type": "content", "header": "Productive Regret", "text": ["Regret should be a teacher, not a jailer.", "Let the memory of what you did wrong sting just enough to remind you why you never want to do it again.", "Let it teach you the value of what you almost lost.", "Let it show you the parts of yourself that need more discipline.", "Learn the lesson, and then gently let the memory go."] },
    { "type": "reflection", "prompt": "What am I most sorry for, and what have I learned from it?" },
    { "type": "content", "header": "The Trap of Pity", "text": ["Do not throw pity parties for yourself.", "When you constantly tell your partner how terrible you are, you are not being accountable.", "You are subtly asking them to validate you.", "You are making them reassure you.", "Stop asking for reassurance when you should be providing stability.", "Stand up. Take the hit. Be better."] },
    { "type": "special", "header": "Read This When You Cannot Stop Overthinking the Past", "text": ["The past is written in ink.", "No amount of anxiety, no amount of replaying the conversation in your head, no amount of wishing you had done it differently will change what happened.", "You are pouring all your energy into a time machine that does not exist.", "Take that energy and pour it into today.", "You cannot change what you did yesterday. But you can decide what kind of person wakes up tomorrow."] },
    { "type": "content", "header": "Making Amends", "text": ["Making amends is different from apologizing.", "An apology is 'I am sorry I broke your vase.'", "Making amends is 'I bought you a new vase, and I am going to be more careful when I walk through this room.'", "Look at the damage you caused. Ask yourself: What can I actually DO to help repair this?"] },
    { "type": "content", "header": "Forgiving the Past Self", "text": ["The version of you that made those mistakes was operating with less wisdom, more fear, and less emotional control.", "You can be disappointed in them.", "But eventually, you have to realize that they were doing the best they could with the broken tools they had.", "You have better tools now.", "Forgive them, so you can move forward."] }
]

output_path = os.path.join("content_data", "ch0_4.json")
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(pages, f, indent=2)

print(f"Generated {len(pages)} pages for Chapters 0-4")
